# Generated by Django 4.1 on 2022-09-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    # https://docs.djangoproject.com/en/4.1/ref/migration-operations/#runsql
    operations = [
        migrations.RunSQL(
            [("INSERT INTO opinions_category (name, description) "
              "VALUES (%s, %s);", [name, desc])]) for name, desc in [
                ('News', 'Opinions on current affairs'),
                ('Sport', 'Opinions on sport'),
                ('Technology', 'Opinions on technology'),
                ('Weather', 'Opinions on the weather'),
                ('Entertainment', 'Opinions on entertainment in general'),
                ('Film', 'Opinions on films/movies'),
                ('Theatre', 'Opinions on theatre'),
                ('Television', 'Opinions on television'),
                ('Cooking', 'Cookery-related opinions'),
                ('Restaurants', 'Opinions on restaurants'),
                ('Motoring', 'Motoring-related opinions'),
                ('Motorbikes', 'Motorbike-related opinions'),
                ('Trains', 'Train-related opinions'),
                ('Planes', 'Plane-related opinions'),
                ('Ships', 'Ship-related opinions'),
                ('Sailing', 'Sailing-related opinions'),
                ('Food', 'Food-related opinions'),
                ('Politics', 'Opinions on politics'),
                ('Tax', 'Opinions on taxes'),
                ('Climate change', 'Opinions on climate change'),
                ('Toys', 'Toy-related opinions'),
                ('Gardening', 'Gardening-related opinions'),
                ('Architecture', 'Architecture-related opinions'),
                ('Travel', 'Travel-related opinions'),
                ('Newspapers', 'Newspaper-related opinions'),
                ('Literature', 'Literature-related opinions'),
                ('Art', 'Art-related opinions'),
            ]
    ]
