# Generated by Django 4.1 on 2022-09-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0003_status_opinion'),
    ]

    operations = [
        migrations.RunSQL(
            [("INSERT INTO opinions_status (name) VALUES (%s);", [name])])
        for name in [
            'Draft', 'Published', 'Withdrawn',
            'Pending Review', 'Under Review', 'Approved', 'Rejected'
        ]
    ]
