# Generated by Django 4.1 on 2022-09-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='excerpt',
            field=models.CharField(blank=True, max_length=150,
                                   verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='content',
            field=models.CharField(max_length=2500, verbose_name='content'),
        ),
    ]
