# Generated by Django 4.1.2 on 2022-10-27 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opinions', '0009_alter_comment_options_pinstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='opinions.comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='opinion',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='opinions.opinion'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
