# Generated by Django 4.1 on 2022-09-05 14:28

from django.db import migrations
from ..constants import (
    STATUS_DRAFT, STATUS_PUBLISHED, STATUS_WITHDRAWN, STATUS_PENDING_REVIEW,
    STATUS_UNDER_REVIEW, STATUS_APPROVED, STATUS_REJECTED
)


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_initial_categories'),
    ]

    operations = [
        migrations.RunSQL(
            [("INSERT INTO categories_status (name) VALUES (%s);", [name])])
        for name in [
            STATUS_DRAFT, STATUS_PUBLISHED, STATUS_WITHDRAWN,
            STATUS_PENDING_REVIEW, STATUS_UNDER_REVIEW, STATUS_APPROVED,
            STATUS_REJECTED
        ]
    ]
