# Generated by Django 4.1 on 2022-09-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_initial_categories'),
    ]

    operations = [
        migrations.RunSQL(
            [("INSERT INTO categories_status (name) VALUES (%s);", [name])])
        for name in [
            'Draft', 'Published', 'Withdrawn',
            'Pending Review', 'Under Review', 'Approved', 'Rejected'
        ]
    ]
