# Generated by Django 4.1 on 2022-09-11 16:25

from django.db import migrations
from ..constants import (
    STATUS_PREVIEW
)


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_add_statuses'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("INSERT INTO categories_status (name) VALUES (%s);", [name])
            ],
            reverse_sql=[
                ("DELETE FROM categories_status WHERE name=%s;", [name])
            ]
        ) for name in [
            STATUS_PREVIEW
        ]
    ]
