# Generated by Django 4.1 on 2022-10-11 15:16

from django.db import migrations
from ..constants import (
    REACTION_AGREE, REACTION_DISAGREE, REACTION_HIDE, REACTION_SHOW,
    REACTION_FOLLOW, REACTION_UNFOLLOW
)


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_add_preview_status'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("INSERT INTO categories_status (name) VALUES (%s);", [name])
            ],
            reverse_sql=[
                ("DELETE FROM categories_status WHERE name=%s;", [name])
            ]
        ) for name in [
            REACTION_AGREE, REACTION_DISAGREE, REACTION_HIDE, REACTION_SHOW,
            REACTION_FOLLOW, REACTION_UNFOLLOW
        ]
    ]
