# Generated by Django 4.1.2 on 2022-10-20 18:33

from django.db import migrations

from ..constants import REACTION_PIN, REACTION_UNPIN


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_add_reaction_statuses'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("INSERT INTO categories_status (name) VALUES (%s);", [name])
            ],
            reverse_sql=[
                ("DELETE FROM categories_status WHERE name=%s;", [name])
            ]
        ) for name in [
            REACTION_PIN, REACTION_UNPIN
        ]
    ]
