# Generated by Django 4.1.3 on 2022-11-15 15:18

from django.db import migrations

from categories.constants import STATUS_DELETED


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_add_pin_unpin_reaction_statuses'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("INSERT INTO categories_status (name) VALUES (%s);", [name])
            ],
            reverse_sql=[
                ("DELETE FROM categories_status WHERE name=%s;", [name])
            ]
        ) for name in [
            STATUS_DELETED
        ]
    ]
