# Generated by Django 4.1 on 2022-08-23 14:42

import cloudinary.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('user_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True, primary_key=True, serialize=False,
                    to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(max_length=250)),
                ('avatar', cloudinary.models.CloudinaryField(
                    default='placeholder', max_length=255,
                    verbose_name='image')),
                ('categories', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['date_joined'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
