# Generated by Django 4.1 on 2022-09-02 14:44
from django.db import migrations, models
from cloudinary.models import CloudinaryField

from soapbox import DEVELOPMENT


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_bio_alter_user_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True, default='avatar_blank', upload_to='soapbox',
                verbose_name='image') if DEVELOPMENT else
            CloudinaryField(default='avatar_blank',
                            max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(
                blank=True, max_length=250, verbose_name='biography'),
        ),
    ]
