# Generated by Django 4.1 on 2022-09-23 17:42

from django.db import migrations

from ..permissions import (
    add_category_permissions, remove_category_permissions
)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_add_author_mod_groups'),
    ]

    # https://docs.djangoproject.com/en/4.1/ref/migration-operations/#runpython

    operations = [
        migrations.RunPython(
            add_category_permissions, remove_category_permissions),
    ]
