# Generated by Django 4.1 on 2022-09-28 15:29

from django.db import migrations

from user.permissions import (
    add_comment_permissions, remove_comment_permissions
)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_add_category_permissions'),
    ]

    # https://docs.djangoproject.com/en/4.1/ref/migration-operations/#runpython

    operations = [
        migrations.RunPython(
            add_comment_permissions, remove_comment_permissions),
    ]
