# Generated by Django 4.1.3 on 2022-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_add_comment_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='previous login'),
        ),
    ]
